name: Bao component base workflow

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  gitlint:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: >
          git config --global --add safe.directory $(realpath .) &&
          make gitlint GITLINT_BASE=${{ github.event.pull_request.base.sha }}

  build:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    strategy:
      matrix:
        platform: ["qemu-aarch64-virt", "qemu-riscv64-virt"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: make PLATFORM=${{ matrix.platform }}

  coding-style:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    strategy:
      matrix:
        platform: ["qemu-aarch64-virt", "qemu-riscv64-virt"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: make PLATFORM=${{ matrix.platform }} format-check

  static-analysis:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    strategy:
      matrix:
        platform: ["qemu-aarch64-virt", "qemu-riscv64-virt"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: make PLATFORM=${{ matrix.platform }} tidy
      - run: make PLATFORM=${{ matrix.platform }} cppcheck

  misra:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    strategy:
      matrix:
        platform: ["qemu-aarch64-virt", "qemu-riscv64-virt"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: make PLATFORM=${{ matrix.platform }} misra-check
